PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX schema: <https://schema.org/>

DELETE {
    ?x dc:contributor|dcterms:contributor ?y
}
INSERT {
    ?x schema:contributor ?y
}
WHERE {
    ?x dc:contributor|dcterms:contributor ?y
}